---

- name: include variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_distribution_release }}.yml"
    - "_{{ (ansible_distribution + '-' + ansible_distribution_major_version) | lower }}.yml"
    - "_{{ ansible_distribution | lower }}.yml"
    - _default.yml
  tags: always

- name: Include install
  ansible.builtin.include_tasks: install.yml
  tags: install

- name: Include configure
  ansible.builtin.include_tasks: configure.yml
  tags: configure

...
