---
- name: Install pro-drivers | install dependencies
  ansible.builtin.yum:
    name: "{{ rstudio_pro_drivers_dependencies }}"
    state: "{{ yum_install_state | default('latest') }}"

- name: Install pro-drivers | download rpm
  ansible.builtin.get_url:
    url: "{{ rstudio_pro_drivers_download_url }}"
    dest: "{{ rstudio_pro_drivers_downloads_path }}/rstudio-drivers_{{ rstudio_pro_drivers_version }}.rpm"
    mode: 0644
    owner: root
    group: root

- name: Install pro-drivers | install rpm
  ansible.builtin.yum:
    name: "{{ rstudio_pro_drivers_downloads_path }}/rstudio-drivers_{{ rstudio_pro_drivers_version }}.rpm"
    state: present
    disable_gpg_check: true
